
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMILLAS END IDENTIFICADOR IGUAL INT LLAVE_DERECHA LLAVE_IZQUIERDA PARENTESIS_DERECHA PARENTESIS_IZQUIERDA PRINTF PUNTO_Y_COMA READ STRING SUMAprogram : IDENTIFICADOR PARENTESIS_IZQUIERDA PARENTESIS_DERECHA LLAVE_IZQUIERDA declarations LLAVE_DERECHAdeclarations : INT IDENTIFICADOR PUNTO_Y_COMA\n                    | READ IDENTIFICADOR PUNTO_Y_COMA\n                    | IDENTIFICADOR IGUAL IDENTIFICADOR SUMA IDENTIFICADOR PUNTO_Y_COMA\n                    | PRINTF PARENTESIS_IZQUIERDA STRING PARENTESIS_DERECHA PUNTO_Y_COMA\n                    | END PUNTO_Y_COMA\n                    | declarations declarations'
    
_lr_action_items = {'IDENTIFICADOR':([0,5,7,8,9,12,13,18,20,21,23,26,27,],[2,6,6,15,16,19,6,-6,-2,-3,25,-5,-4,]),'$end':([1,14,],[0,-1,]),'PARENTESIS_IZQUIERDA':([2,10,],[3,17,]),'PARENTESIS_DERECHA':([3,22,],[4,24,]),'LLAVE_IZQUIERDA':([4,],[5,]),'INT':([5,7,13,18,20,21,26,27,],[8,8,8,-6,-2,-3,-5,-4,]),'READ':([5,7,13,18,20,21,26,27,],[9,9,9,-6,-2,-3,-5,-4,]),'PRINTF':([5,7,13,18,20,21,26,27,],[10,10,10,-6,-2,-3,-5,-4,]),'END':([5,7,13,18,20,21,26,27,],[11,11,11,-6,-2,-3,-5,-4,]),'IGUAL':([6,],[12,]),'LLAVE_DERECHA':([7,13,18,20,21,26,27,],[14,-7,-6,-2,-3,-5,-4,]),'PUNTO_Y_COMA':([11,15,16,24,25,],[18,20,21,26,27,]),'STRING':([17,],[22,]),'SUMA':([19,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([5,7,13,],[7,13,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> IDENTIFICADOR PARENTESIS_IZQUIERDA PARENTESIS_DERECHA LLAVE_IZQUIERDA declarations LLAVE_DERECHA','program',6,'p_program','app.py',55),
  ('declarations -> INT IDENTIFICADOR PUNTO_Y_COMA','declarations',3,'p_declarations','app.py',59),
  ('declarations -> READ IDENTIFICADOR PUNTO_Y_COMA','declarations',3,'p_declarations','app.py',60),
  ('declarations -> IDENTIFICADOR IGUAL IDENTIFICADOR SUMA IDENTIFICADOR PUNTO_Y_COMA','declarations',6,'p_declarations','app.py',61),
  ('declarations -> PRINTF PARENTESIS_IZQUIERDA STRING PARENTESIS_DERECHA PUNTO_Y_COMA','declarations',5,'p_declarations','app.py',62),
  ('declarations -> END PUNTO_Y_COMA','declarations',2,'p_declarations','app.py',63),
  ('declarations -> declarations declarations','declarations',2,'p_declarations','app.py',64),
]
